ALTER TABLE HOMEINSURANCE.CLAIM ADD CONSTRAINT PK_CLAIM PRIMARY KEY (CLAIM_ID);
ALTER TABLE HOMEINSURANCE.CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE HOMEINSURANCE.POLICY ADD CONSTRAINT PK_POLICY PRIMARY KEY (POLICY_ID);

ALTER TABLE HOMEINSURANCE.CLAIM ADD CONSTRAINT FK_CLAIM_POLICY FOREIGN KEY (POLICY_ID) REFERENCES HOMEINSURANCE.POLICY (POLICY_ID);
ALTER TABLE HOMEINSURANCE.POLICY ADD CONSTRAINT FK_POLICY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES HOMEINSURANCE.CUSTOMER (CUSTOMER_ID);
ALTER TABLE HOMEINSURANCE.POLICY_OPTION ADD CONSTRAINT FK_OPTIONS_POLICY FOREIGN KEY (POLICY_ID) REFERENCES HOMEINSURANCE.POLICY (POLICY_ID);
ALTER TABLE HOMEINSURANCE.POLICY_RISK ADD CONSTRAINT FK_RISK_POLICY FOREIGN KEY (POLICY_ID) REFERENCES HOMEINSURANCE.POLICY (POLICY_ID);
ALTER TABLE HOMEINSURANCE.POLICY_COVERAGE ADD CONSTRAINT FK_COVERAGE_POLICY FOREIGN KEY (POLICY_ID) REFERENCES HOMEINSURANCE.POLICY (POLICY_ID);

CREATE OR REPLACE TRIGGER trg_c_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.customer
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/

CREATE OR REPLACE TRIGGER trg_p_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.policy
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/

CREATE OR REPLACE TRIGGER trg_pc_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.policy_coverage
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/

CREATE OR REPLACE TRIGGER trg_po_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.policy_option
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/   

CREATE OR REPLACE TRIGGER trg_pr_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.policy_risk
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/  

CREATE OR REPLACE TRIGGER trg_cl_last_update
              BEFORE INSERT OR UPDATE ON HOMEINSURANCE.claim
                 FOR EACH ROW
   BEGIN
      :NEW.last_change := sysdate;
   END;
/
